### ISSUE TITLE
when i run the code ,there were some errors?

### ISSUE THREAD

**Issue by YoudianguaiYi** [zhixuhao/unet#155]
In the model.py  line5 ：TypeError: __init__() missing 1 required positional argument: 'nb_col'，Is this keras's version not match??

**Comment by hala3** [comment]
me also i have this error


299/300 [============================>.] - ETA: 0s - loss: 0.1959 - acc: 0.9215Epoch 00001: loss improved from inf to 0.19559, saving mod300/300 [==============================] - 87s 290ms/step - loss: 0.1956 - acc: 0.9216
13/30 [============>.................] - ETA: 1sTraceback (most recent call last):
  File "main.py", line 21, in <module>
    results = model.predict_generator(testGene,30,verbose=1)
  File "/home/hala/anaconda3/envs/py35gpu/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/hala/anaconda3/envs/py35gpu/lib/python3.5/site-packages/keras/engine/training.py", line 2407, in predict_generator
    generator_output = next(output_generator)
  File "/home/hala/anaconda3/envs/py35gpu/lib/python3.5/site-packages/keras/utils/data_utils.py", line 727, in get
    raise StopIteration()
StopIteration

**Comment by sarathsrk** [comment]
yes, Keras version mismatch!
