### ISSUE TITLE
about the init

### ISSUE THREAD

**Issue by neneneha** [zhixuhao/unet#21]
Hi,

Thanks for this implementation.But when i run unet.py,there was something wrong.can you give me some suggestions?thank you very much!
Using TensorFlow backend.
loading data
------------------------------
load train images...
------------------------------
/home/test/Desktop/unet-masters/data.py:216: RuntimeWarning: Mean of empty slice.
  mean = imgs_train.mean(axis=0)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
------------------------------
load test images...
------------------------------
/home/test/Desktop/unet-masters/data.py:230: RuntimeWarning: Mean of empty slice.
  mean = imgs_test.mean(axis=0)
loading data done
Traceback (most recent call last):
  File "unet.py", line 168, in <module>
    myunet.train()
  File "unet.py", line 152, in train
    model = self.get_unet()
  File "unet.py", line 85, in get_unet
    conv1 = Conv2D(64, 3, activation='relu', padding='same', kernel_initializer='he_normal')(inputs)
TypeError: __init__() takes at least 4 arguments (4 given)

**Comment by xuebaojiang** [comment]
The TensorFlow version is not suitable，i use 1.3.0
